package ProjetoA3_BlueWorld.telas;

/**
 *
 * @author //Grupo 04\\
 */

import javax.swing.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import ProjetoA3_BlueWorld.bd.UsuarioDAO;
import ProjetoA3_BlueWorld.modelo.Usuario;

public class TelaCadastro extends javax.swing.JFrame {

    private UsuarioDAO usuarioDAO;

    public TelaCadastro() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Definir campo Nome Completo
        NomeComplet.setBackground(new Color(0, 0, 0, 0));
        NomeComplet.setBorder(null);
        NomeComplet.setOpaque(false);
        
        // Definir campo Email
        Email.setBackground(new Color(0, 0, 0, 0));
        Email.setBorder(null);
        Email.setOpaque(false);
        
        // Definir campo Confirmar Email
        ConfEmail.setBackground(new Color(0, 0, 0, 0));
        ConfEmail.setBorder(null);
        ConfEmail.setOpaque(false);
        
        // Definir campo Senha
        Pass.setBackground(new Color(0, 0, 0, 0));
        Pass.setBorder(null);
        Pass.setOpaque(false);
        
        // Definir campo Confirmar Senha
        ConfPass.setBackground(new Color(0, 0, 0, 0));
        ConfPass.setBorder(null);
        ConfPass.setOpaque(false);
        
        // Definir campo CPF
        CPF.setBackground(new Color(0, 0, 0, 0));
        CPF.setBorder(null);
        CPF.setOpaque(false);
        
        // Definir campo CEP
        CEP.setBackground(new Color(0, 0, 0, 0));
        CEP.setBorder(null);
        CEP.setOpaque(false);
        
        // Definir campo Rua
        Rua.setBackground(new Color(0, 0, 0, 0));
        Rua.setBorder(null);
        Rua.setOpaque(false);
        
        // Definir campo Rua
        Rua.setBackground(new Color(0, 0, 0, 0));
        Rua.setBorder(null);
        Rua.setOpaque(false);

        usuarioDAO = new UsuarioDAO();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeComplet = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        ConfEmail = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();
        ConfPass = new javax.swing.JPasswordField();
        CPF = new javax.swing.JTextField();
        CEP = new javax.swing.JTextField();
        Rua = new javax.swing.JTextField();
        Confirmar = new javax.swing.JToggleButton();
        Limpar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SingUp");
        getContentPane().setLayout(null);

        NomeComplet.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        NomeComplet.setForeground(new java.awt.Color(255, 255, 255));
        NomeComplet.setText("Nome Completo");
        NomeComplet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCompletActionPerformed(evt);
            }
        });
        getContentPane().add(NomeComplet);
        NomeComplet.setBounds(200, 180, 340, 60);

        Email.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("E-mail");
        getContentPane().add(Email);
        Email.setBounds(200, 280, 330, 50);

        ConfEmail.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ConfEmail.setForeground(new java.awt.Color(255, 255, 255));
        ConfEmail.setText("E-mail");
        getContentPane().add(ConfEmail);
        ConfEmail.setBounds(200, 370, 330, 50);

        Pass.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Pass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Pass);
        Pass.setBounds(200, 470, 330, 50);

        ConfPass.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ConfPass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ConfPass);
        ConfPass.setBounds(200, 570, 330, 50);

        CPF.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CPF.setForeground(new java.awt.Color(255, 255, 255));
        CPF.setText("CPF");
        CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFActionPerformed(evt);
            }
        });
        getContentPane().add(CPF);
        CPF.setBounds(810, 180, 330, 50);

        CEP.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CEP.setForeground(new java.awt.Color(255, 255, 255));
        CEP.setText("CEP");
        CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPActionPerformed(evt);
            }
        });
        getContentPane().add(CEP);
        CEP.setBounds(820, 280, 330, 50);

        Rua.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Rua.setForeground(new java.awt.Color(255, 255, 255));
        Rua.setText("Rua");
        Rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuaActionPerformed(evt);
            }
        });
        getContentPane().add(Rua);
        Rua.setBounds(820, 370, 330, 50);

        Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirmar.png"))); // NOI18N
        Confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmarMouseClicked(evt);
            }
        });
        getContentPane().add(Confirmar);
        Confirmar.setBounds(640, 610, 160, 50);

        Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Limpar.png"))); // NOI18N
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        getContentPane().add(Limpar);
        Limpar.setBounds(820, 610, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelaCadastro.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1420, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuaActionPerformed

    }//GEN-LAST:event_RuaActionPerformed

    private void CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEPActionPerformed

    private void ConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarMouseClicked
        String nomeCompleto = NomeComplet.getText();
        String email = Email.getText();
        String confirmar_email = ConfEmail.getText();
        String senha = new String(Pass.getPassword());
        String confirmar_senha = new String (ConfPass.getPassword());
        String cpf = CPF.getText();
        String cep = CEP.getText();
        String rua = Rua.getText();
        String tipo_usuario = "comum";
        
        // Verificação de email e senha
                if (!email.equals(confirmar_email)) {
                    JOptionPane.showMessageDialog(TelaCadastro.this, "Os emails não coincidem.");
                    return;
                }

                if (!senha.equals(confirmar_senha)) {
                    JOptionPane.showMessageDialog(TelaCadastro.this, "As senhas não coincidem.");
                    return;
                }

        Usuario u = new Usuario(nomeCompleto, email, senha, cpf, cep, rua, tipo_usuario);

        try {
            usuarioDAO.cadastrar(u);
            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");
            LoginTela telaLogin = new LoginTela();
            telaLogin.setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário: " + e.getMessage());
        }
    
    }//GEN-LAST:event_ConfirmarMouseClicked

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        NomeComplet.setText("");
        Email.setText("");
        ConfEmail.setText("");
        Pass.setText("");
        ConfPass.setText("");
        CPF.setText("");
        CEP.setText("");
        Rua.setText("");
    }//GEN-LAST:event_LimparActionPerformed

    private void NomeCompletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCompletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCompletActionPerformed

    private void CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CEP;
    private javax.swing.JTextField CPF;
    private javax.swing.JTextField ConfEmail;
    private javax.swing.JPasswordField ConfPass;
    private javax.swing.JToggleButton Confirmar;
    private javax.swing.JTextField Email;
    private javax.swing.JToggleButton Limpar;
    private javax.swing.JTextField NomeComplet;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JTextField Rua;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
