/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoA3_BlueWorld.telas;

import java.awt.Color;

/**
 *
 * @author Pichau
 */
public class TelaComum extends javax.swing.JFrame {

    /**
     * Creates new form TelaComun
     */
    public TelaComum() {
        initComponents();
        
        
        // Definir campo Bairro
        Inicio.setBackground(new Color(0, 0, 0, 0));
        Inicio.setBorder(null);
        Inicio.setOpaque(false);
        
        // Definir campo Bairro
        CadastrarOcorrencia.setBackground(new Color(0, 0, 0, 0));
        CadastrarOcorrencia.setBorder(null);
        CadastrarOcorrencia.setOpaque(false);
        
        // Definir campo Bairro
        Sair.setBackground(new Color(0, 0, 0, 0));
        Sair.setBorder(null);
        Sair.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JToggleButton();
        CadastrarOcorrencia = new javax.swing.JToggleButton();
        Sair = new javax.swing.JToggleButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Inicio.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setText("Início");
        getContentPane().add(Inicio);
        Inicio.setBounds(50, 150, 90, 36);

        CadastrarOcorrencia.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        CadastrarOcorrencia.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarOcorrencia.setText("Cadastrar Ocorrência");
        CadastrarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarOcorrenciaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarOcorrencia);
        CadastrarOcorrencia.setBounds(50, 230, 200, 36);

        Sair.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Sair.setText("Sair");
        getContentPane().add(Sair);
        Sair.setBounds(1280, 20, 60, 31);

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pichau\\OneDrive\\Área de Trabalho\\20241_usjt_psc_noite_intro_git\\ProjetoA3_BlueWorld\\src\\main\\resources\\TelaComum.png")); // NOI18N
        Fundo.setText("jLabel1");
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 1360, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarOcorrenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarOcorrenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CadastrarOcorrencia;
    private javax.swing.JLabel Fundo;
    private javax.swing.JToggleButton Inicio;
    private javax.swing.JToggleButton Sair;
    // End of variables declaration//GEN-END:variables
}
