/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoA3_BlueWorld.telas;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Pichau
 */
public class TelaComum extends javax.swing.JFrame {

    /**
     * Creates new form TelaComun
     */
    public TelaComum() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Definir campo Bairro
        Inicio.setBackground(new Color(0, 0, 0, 0));
        Inicio.setBorder(null);
        Inicio.setOpaque(false);
        
        // Definir campo Bairro
        CadastrarOcorrencia.setBackground(new Color(0, 0, 0, 0));
        CadastrarOcorrencia.setBorder(null);
        CadastrarOcorrencia.setOpaque(false);
        
        // Definir campo Bairro
        Sair.setBackground(new Color(0, 0, 0, 0));
        Sair.setBorder(null);
        Sair.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JToggleButton();
        CadastrarOcorrencia = new javax.swing.JToggleButton();
        Sair = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Inicio.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setText("Início");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        getContentPane().add(Inicio);
        Inicio.setBounds(10, 141, 150, 50);

        CadastrarOcorrencia.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        CadastrarOcorrencia.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarOcorrencia.setText("Cadastrar Ocorrência");
        CadastrarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarOcorrenciaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarOcorrencia);
        CadastrarOcorrencia.setBounds(10, 221, 260, 50);

        Sair.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(1220, 20, 140, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome do Rio ", "Estado ", "Bairro", "Nível de Poluição", "Tipo de Poluição", "Data da Ocorrência"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 100, 1040, 650);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelaComum.png"))); // NOI18N
        Fundo.setText("jLabel1");
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 1360, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarOcorrenciaActionPerformed
        TelaCadastro janelaPrincipal = new TelaCadastro();
        janelaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_CadastrarOcorrenciaActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        LoginTela janelaPrincipal = new LoginTela();
        janelaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_InicioActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CadastrarOcorrencia;
    private javax.swing.JLabel Fundo;
    private javax.swing.JToggleButton Inicio;
    private javax.swing.JToggleButton Sair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
